spring:
  redis:
    #cluster:
    #  nodes: 127.0.0.1:9000,127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003,127.0.0.1:9004,127.0.0.1:9005
    #  max-redirects: 3
    #redis机器ip
    host: 172.20.11.233
    #redis端口
    port: 16379
    #redis密码
    password: stock
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000
    lettuce: #使用jedis：当多线程使用同一个连接时，是线程不安全的。所以要使用连接池，为每个jedis实例分配一个连接。
             #使用Lettuce：当多线程使用同一连接实例时，是线程安全的。
      pool:
        #连接池中的最大空闲连接
        max-idle: 100
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1